######################################################################
# Automatically generated by qmake (1.07a) Mon Feb 7 19:00:32 2011
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += main.cpp
