# @_laname@ - a libtool library file
# Generated by CMake - GNU libtool
#
# Please DO NOT delete this file!
# It is necessary for linking the library.

# The name that we can dlopen(3).
dlname='@_library_name_2@'

# Names of this library.
library_names='@_library_name_1@ @_library_name_2@ @_library_name_3@'

# The name of the static archive.
old_library=''

# Libraries that this one depends upon.
dependency_libs=''

# Version information for @_name@.
current=@_version_current@
age=@_version_age@
revision=@_version_revision@

# Is this an already installed library?
installed=yes

# Should we warn about portability when linking against -modules?
shouldnotlink=@_shouldnotlink@

# Files to dlopen/dlpreopen
dlopen=''
dlpreopen=''

# Directory that this library needs to be installed in:
libdir='@_libdir@'
