#!/bin/bash

top_srcdir=${1}
top_builddir=${2}
kde_libs_htmldir=${3}
export QTDOCDIR=${4}

if [[ ! -d "${top_srcdir}/doc/common/" ]]; then
	export DOXDATA=${kde_libs_htmldir}/en/common
fi

abs_top_srcdir=$(cd ${top_srcdir} && pwd)

rm -rf ${top_builddir}/${kde_libs_htmldir}/en
mkdir -p ${top_builddir}/${kde_libs_htmldir}/en
cd ${top_builddir}/${kde_libs_htmldir}/en
${abs_top_srcdir}/admin/doxygen.sh --modulename --installdir=${top_builddir}/${kde_libs_htmldir}/en ${abs_top_srcdir}
